
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov 16 2025 11:37:55 CST (Nov 16 2025 17:37:55 UTC)

// Verification Directory fv/clk_gate_virtuoso 

module clk_gate_virtuoso(clk, is_error, rst_n, gated_clk);
  input clk, is_error, rst_n;
  output gated_clk;
  wire clk, is_error, rst_n;
  wire gated_clk;
  wire [3:0] cnt;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, clk_en,
       is_gated, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_24, n_42;
  CLKGATETST_X1 u_icg(.E (clk_en), .CK (clk), .SE (1'b0), .GCK
       (gated_clk));
  DFF_X1 \cnt_reg[2] (.CK (clk), .D (n_14), .Q (cnt[2]), .QN
       (UNCONNECTED));
  DFF_X1 \cnt_reg[3] (.CK (clk), .D (n_13), .Q (cnt[3]), .QN
       (UNCONNECTED0));
  AND2_X1 g262__8780(.A1 (n_12), .A2 (n_5), .ZN (n_14));
  AND2_X1 g263__4296(.A1 (n_11), .A2 (n_5), .ZN (n_13));
  HA_X1 g264__3772(.A (n_7), .B (cnt[2]), .CO (n_11), .S (n_12));
  DFF_X1 \cnt_reg[0] (.CK (clk), .D (n_10), .Q (cnt[0]), .QN
       (UNCONNECTED1));
  DFF_X1 \cnt_reg[1] (.CK (clk), .D (n_9), .Q (cnt[1]), .QN
       (UNCONNECTED2));
  OAI21_X1 g267__1474(.A (n_2), .B1 (cnt[0]), .B2 (n_6), .ZN (n_10));
  SDFF_X1 is_gated_reg(.CK (clk), .D (n_4), .SE (n_3), .SI (n_24), .Q
       (is_gated), .QN (clk_en));
  AND2_X1 g269__4547(.A1 (n_8), .A2 (n_5), .ZN (n_9));
  HA_X1 g270__9682(.A (cnt[1]), .B (cnt[0]), .CO (n_7), .S (n_8));
  INV_X1 g271(.A (n_5), .ZN (n_6));
  NOR3_X1 g272__2683(.A1 (cnt[3]), .A2 (clk_en), .A3 (n_3), .ZN (n_5));
  AOI21_X1 g273__1309(.A (clk_en), .B1 (cnt[3]), .B2 (is_gated), .ZN
       (n_4));
  NAND2_X1 g274__6877(.A1 (n_1), .A2 (n_24), .ZN (n_3));
  NAND2_X1 g275__2900(.A1 (n_42), .A2 (n_24), .ZN (n_2));
  INV_X1 drc_bufs299(.A (n_42), .ZN (n_1));
  CLKBUF_X1 drc_buf_sp(.A (rst_n), .Z (n_24));
  CLKBUF_X1 drc_buf_sp305(.A (is_error), .Z (n_42));
endmodule

