
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov  1 2025 20:51:19 CDT (Nov  2 2025 01:51:19 UTC)

// Verification Directory fv/clock_gate 

module clock_gate(clk, is_error, rst_n, gated_clk);
  input clk, is_error, rst_n;
  output gated_clk;
  wire clk, is_error, rst_n;
  wire gated_clk;
  wire [4:0] cnt;
  wire UNCONNECTED, UNCONNECTED0, is_gated, n_0, n_1, n_2, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_33;
  wire n_39;
  DFF_X1 \cnt_reg[2] (.CK (clk), .D (n_29), .Q (cnt[2]), .QN
       (UNCONNECTED));
  INV_X1 g583(.A (n_28), .ZN (n_29));
  DFF_X1 \cnt_reg[3] (.CK (clk), .D (n_26), .Q (cnt[3]), .QN
       (UNCONNECTED0));
  AOI22_X1 g584__8780(.A1 (cnt[2]), .A2 (n_23), .B1 (n_4), .B2 (n_27),
       .ZN (n_28));
  SDFF_X1 \cnt_reg[1] (.CK (clk), .D (n_27), .SE (cnt[1]), .SI (n_20),
       .Q (cnt[1]), .QN (n_0));
  SDFF_X1 is_gated_reg(.CK (clk), .D (n_21), .SE (n_12), .SI (n_39), .Q
       (is_gated), .QN (n_7));
  DFF_X1 \cnt_reg[0] (.CK (clk), .D (n_25), .Q (cnt[0]), .QN (n_2));
  NAND2_X1 g587__4296(.A1 (n_22), .A2 (n_24), .ZN (n_26));
  NAND2_X1 g588__3772(.A1 (n_18), .A2 (n_14), .ZN (n_25));
  NAND2_X1 g589__1474(.A1 (cnt[3]), .A2 (n_16), .ZN (n_24));
  OAI21_X1 g590__4547(.A (n_19), .B1 (cnt[1]), .B2 (n_17), .ZN (n_23));
  NAND3_X1 g594__9682(.A1 (cnt[2]), .A2 (cnt[1]), .A3 (n_27), .ZN
       (n_22));
  AND2_X1 g592__2683(.A1 (n_33), .A2 (is_gated), .ZN (n_21));
  INV_X1 g593(.A (n_19), .ZN (n_20));
  MUX2_X1 g595__1309(.A (n_17), .B (n_15), .S (cnt[0]), .Z (n_18));
  OAI21_X1 g596__6877(.A (n_39), .B1 (n_8), .B2 (n_11), .ZN (n_19));
  NAND2_X1 g591__2900(.A1 (n_15), .A2 (n_14), .ZN (n_16));
  NOR2_X1 g597__2391(.A1 (n_2), .A2 (n_17), .ZN (n_27));
  NAND2_X1 g599__7118(.A1 (n_9), .A2 (n_6), .ZN (n_14));
  OR2_X1 g601__8757(.A1 (n_11), .A2 (n_1), .ZN (n_12));
  NAND2_X1 g600__1786(.A1 (n_11), .A2 (n_39), .ZN (n_15));
  INV_X1 g602(.A (n_9), .ZN (n_10));
  NOR3_X1 g603__5953(.A1 (cnt[0]), .A2 (cnt[3]), .A3 (n_7), .ZN (n_8));
  OR2_X1 g605__5703(.A1 (cnt[3]), .A2 (n_5), .ZN (n_17));
  NOR3_X1 g604__7114(.A1 (cnt[2]), .A2 (cnt[0]), .A3 (cnt[1]), .ZN
       (n_9));
  AND2_X1 g607__5266(.A1 (is_error), .A2 (n_7), .ZN (n_11));
  INV_X1 g608(.A (n_5), .ZN (n_6));
  NOR2_X1 g606__2250(.A1 (cnt[2]), .A2 (n_0), .ZN (n_4));
  AND2_X1 g609__6083(.A1 (n_7), .A2 (clk), .ZN (gated_clk));
  NAND2_X1 g610__2703(.A1 (is_gated), .A2 (n_39), .ZN (n_5));
  NAND2_X1 g2(.A1 (n_10), .A2 (cnt[3]), .ZN (n_33));
  INV_X1 drc_bufs625(.A (n_39), .ZN (n_1));
  CLKBUF_X1 drc_buf_sp(.A (rst_n), .Z (n_39));
endmodule

