
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov 15 2025 23:50:55 CST (Nov 16 2025 05:50:55 UTC)

// Verification Directory fv/clk_gate_virtuoso 

module clk_gate_virtuoso(clk, is_error, rst_n, clk_en);
  input clk, is_error, rst_n;
  output clk_en;
  wire clk, is_error, rst_n;
  wire clk_en;
  wire [3:0] cnt;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14;
  DFF_X1 \cnt_reg[2] (.CK (clk), .D (n_14), .Q (cnt[2]), .QN
       (UNCONNECTED));
  DFF_X1 \cnt_reg[3] (.CK (clk), .D (n_13), .Q (cnt[3]), .QN
       (UNCONNECTED0));
  DFF_X1 \cnt_reg[0] (.CK (clk), .D (n_11), .Q (cnt[0]), .QN
       (UNCONNECTED1));
  AND2_X1 g264__8780(.A1 (n_10), .A2 (n_12), .ZN (n_14));
  DFF_X1 \cnt_reg[1] (.CK (clk), .D (n_8), .Q (cnt[1]), .QN
       (UNCONNECTED2));
  AND2_X1 g265__4296(.A1 (n_9), .A2 (n_12), .ZN (n_13));
  OAI21_X1 g269__3772(.A (n_2), .B1 (cnt[0]), .B2 (n_7), .ZN (n_11));
  HA_X1 g266__1474(.A (n_4), .B (cnt[2]), .CO (n_9), .S (n_10));
  SDFF_X1 is_gated_reg(.CK (clk), .D (n_3), .SE (n_6), .SI (rst_n), .Q
       (UNCONNECTED3), .QN (clk_en));
  AND2_X1 g271__4547(.A1 (n_5), .A2 (n_12), .ZN (n_8));
  INV_X1 g273(.A (n_12), .ZN (n_7));
  NOR3_X1 g274__9682(.A1 (cnt[3]), .A2 (clk_en), .A3 (n_6), .ZN (n_12));
  HA_X1 g272__2683(.A (cnt[1]), .B (cnt[0]), .CO (n_4), .S (n_5));
  AOI21_X1 g275__1309(.A (clk_en), .B1 (cnt[3]), .B2 (1'b1), .ZN (n_3));
  NAND2_X1 g276__6877(.A1 (n_0), .A2 (rst_n), .ZN (n_6));
  NAND2_X1 g277__2900(.A1 (is_error), .A2 (rst_n), .ZN (n_2));
  INV_X1 g278(.A (is_error), .ZN (n_0));
endmodule

