
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov 11 2025 11:06:32 CST (Nov 11 2025 17:06:32 UTC)

// Verification Directory fv/DVM 

module invChain_LENGTH8_DRIVER_L1(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_1(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_2(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_3(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_4(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_5(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_6(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_7(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_8(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_9(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_10(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_11(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_12(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_13(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_14(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_15(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_16(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_17(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_18(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_19(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_20(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_21(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_22(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_23(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_24(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_25(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_26(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_27(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_28(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_29(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_30(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_1(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_2(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_3(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_4(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_5(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_6(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_7(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module TRC_TUNING_WIDTH8_TUNING_WIDTH_LOW3(data_in, tuning_bits,
     data_out);
  input data_in;
  input [7:0] tuning_bits;
  output data_out;
  wire data_in;
  wire [7:0] tuning_bits;
  wire data_out;
  wire [31:0] inv_chain_out;
  wire [8:0] inv_chain_small_out;
  wire mux1_out, n_1, n_3, n_4, n_5, n_10, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_78, n_79, n_80, n_83, n_85, n_91, n_92;
  wire n_93, n_94, n_95, n_98, n_100, n_179, n_181, n_182;
  wire n_183, n_184;
  invChain_LENGTH8_DRIVER_L1 \TRC_part_big[0].u_inv_chain8 (.in_data
       (data_in), .out_data (inv_chain_out[1]));
  invChain_LENGTH8_DRIVER_L1_1 \TRC_part_big[1].u_inv_chain8 (.in_data
       (inv_chain_out[1]), .out_data (inv_chain_out[2]));
  invChain_LENGTH8_DRIVER_L1_2 \TRC_part_big[2].u_inv_chain8 (.in_data
       (inv_chain_out[2]), .out_data (inv_chain_out[3]));
  invChain_LENGTH8_DRIVER_L1_3 \TRC_part_big[3].u_inv_chain8 (.in_data
       (inv_chain_out[3]), .out_data (inv_chain_out[4]));
  invChain_LENGTH8_DRIVER_L1_4 \TRC_part_big[4].u_inv_chain8 (.in_data
       (inv_chain_out[4]), .out_data (inv_chain_out[5]));
  invChain_LENGTH8_DRIVER_L1_5 \TRC_part_big[5].u_inv_chain8 (.in_data
       (inv_chain_out[5]), .out_data (inv_chain_out[6]));
  invChain_LENGTH8_DRIVER_L1_6 \TRC_part_big[6].u_inv_chain8 (.in_data
       (inv_chain_out[6]), .out_data (inv_chain_out[7]));
  invChain_LENGTH8_DRIVER_L1_7 \TRC_part_big[7].u_inv_chain8 (.in_data
       (inv_chain_out[7]), .out_data (inv_chain_out[8]));
  invChain_LENGTH8_DRIVER_L1_8 \TRC_part_big[8].u_inv_chain8 (.in_data
       (inv_chain_out[8]), .out_data (inv_chain_out[9]));
  invChain_LENGTH8_DRIVER_L1_9 \TRC_part_big[9].u_inv_chain8 (.in_data
       (inv_chain_out[9]), .out_data (inv_chain_out[10]));
  invChain_LENGTH8_DRIVER_L1_10 \TRC_part_big[10].u_inv_chain8
       (.in_data (inv_chain_out[10]), .out_data (inv_chain_out[11]));
  invChain_LENGTH8_DRIVER_L1_11 \TRC_part_big[11].u_inv_chain8
       (.in_data (inv_chain_out[11]), .out_data (inv_chain_out[12]));
  invChain_LENGTH8_DRIVER_L1_12 \TRC_part_big[12].u_inv_chain8
       (.in_data (inv_chain_out[12]), .out_data (inv_chain_out[13]));
  invChain_LENGTH8_DRIVER_L1_13 \TRC_part_big[13].u_inv_chain8
       (.in_data (inv_chain_out[13]), .out_data (inv_chain_out[14]));
  invChain_LENGTH8_DRIVER_L1_14 \TRC_part_big[14].u_inv_chain8
       (.in_data (inv_chain_out[14]), .out_data (inv_chain_out[15]));
  invChain_LENGTH8_DRIVER_L1_15 \TRC_part_big[15].u_inv_chain8
       (.in_data (inv_chain_out[15]), .out_data (inv_chain_out[16]));
  invChain_LENGTH8_DRIVER_L1_16 \TRC_part_big[16].u_inv_chain8
       (.in_data (inv_chain_out[16]), .out_data (inv_chain_out[17]));
  invChain_LENGTH8_DRIVER_L1_17 \TRC_part_big[17].u_inv_chain8
       (.in_data (inv_chain_out[17]), .out_data (inv_chain_out[18]));
  invChain_LENGTH8_DRIVER_L1_18 \TRC_part_big[18].u_inv_chain8
       (.in_data (inv_chain_out[18]), .out_data (inv_chain_out[19]));
  invChain_LENGTH8_DRIVER_L1_19 \TRC_part_big[19].u_inv_chain8
       (.in_data (inv_chain_out[19]), .out_data (inv_chain_out[20]));
  invChain_LENGTH8_DRIVER_L1_20 \TRC_part_big[20].u_inv_chain8
       (.in_data (inv_chain_out[20]), .out_data (inv_chain_out[21]));
  invChain_LENGTH8_DRIVER_L1_21 \TRC_part_big[21].u_inv_chain8
       (.in_data (inv_chain_out[21]), .out_data (inv_chain_out[22]));
  invChain_LENGTH8_DRIVER_L1_22 \TRC_part_big[22].u_inv_chain8
       (.in_data (inv_chain_out[22]), .out_data (inv_chain_out[23]));
  invChain_LENGTH8_DRIVER_L1_23 \TRC_part_big[23].u_inv_chain8
       (.in_data (inv_chain_out[23]), .out_data (inv_chain_out[24]));
  invChain_LENGTH8_DRIVER_L1_24 \TRC_part_big[24].u_inv_chain8
       (.in_data (inv_chain_out[24]), .out_data (inv_chain_out[25]));
  invChain_LENGTH8_DRIVER_L1_25 \TRC_part_big[25].u_inv_chain8
       (.in_data (inv_chain_out[25]), .out_data (inv_chain_out[26]));
  invChain_LENGTH8_DRIVER_L1_26 \TRC_part_big[26].u_inv_chain8
       (.in_data (inv_chain_out[26]), .out_data (inv_chain_out[27]));
  invChain_LENGTH8_DRIVER_L1_27 \TRC_part_big[27].u_inv_chain8
       (.in_data (inv_chain_out[27]), .out_data (inv_chain_out[28]));
  invChain_LENGTH8_DRIVER_L1_28 \TRC_part_big[28].u_inv_chain8
       (.in_data (inv_chain_out[28]), .out_data (inv_chain_out[29]));
  invChain_LENGTH8_DRIVER_L1_29 \TRC_part_big[29].u_inv_chain8
       (.in_data (inv_chain_out[29]), .out_data (inv_chain_out[30]));
  invChain_LENGTH8_DRIVER_L1_30 \TRC_part_big[30].u_inv_chain8
       (.in_data (inv_chain_out[30]), .out_data (inv_chain_out[31]));
  invChain_LENGTH1_DRIVER_L1 \TRC_part_small[0].u_inv_chain1 (.in_data
       (mux1_out), .out_data (inv_chain_small_out[1]));
  invChain_LENGTH1_DRIVER_L1_1 \TRC_part_small[1].u_inv_chain1
       (.in_data (inv_chain_small_out[1]), .out_data
       (inv_chain_small_out[2]));
  invChain_LENGTH1_DRIVER_L1_2 \TRC_part_small[2].u_inv_chain1
       (.in_data (inv_chain_small_out[2]), .out_data
       (inv_chain_small_out[3]));
  invChain_LENGTH1_DRIVER_L1_3 \TRC_part_small[3].u_inv_chain1
       (.in_data (inv_chain_small_out[3]), .out_data
       (inv_chain_small_out[4]));
  invChain_LENGTH1_DRIVER_L1_4 \TRC_part_small[4].u_inv_chain1
       (.in_data (inv_chain_small_out[4]), .out_data
       (inv_chain_small_out[5]));
  invChain_LENGTH1_DRIVER_L1_5 \TRC_part_small[5].u_inv_chain1
       (.in_data (inv_chain_small_out[5]), .out_data
       (inv_chain_small_out[6]));
  invChain_LENGTH1_DRIVER_L1_6 \TRC_part_small[6].u_inv_chain1
       (.in_data (inv_chain_small_out[6]), .out_data
       (inv_chain_small_out[7]));
  invChain_LENGTH1_DRIVER_L1_7 \TRC_part_small[7].u_inv_chain1
       (.in_data (inv_chain_small_out[7]), .out_data
       (inv_chain_small_out[8]));
  INV_X1 g2161(.A (n_68), .ZN (mux1_out));
  AOI21_X1 g2162__8780(.A (n_67), .B1 (inv_chain_out[31]), .B2 (n_46),
       .ZN (n_68));
  OAI21_X2 g2163__4296(.A (n_66), .B1 (n_60), .B2 (n_27), .ZN (n_67));
  INV_X1 g2164(.A (n_65), .ZN (n_66));
  OAI33_X1 g2165__3772(.A1 (n_64), .A2 (n_57), .A3 (tuning_bits[6]),
       .B1 (n_63), .B2 (n_19), .B3 (tuning_bits[7]), .ZN (n_65));
  AOI221_X1 g2166__1474(.A (n_62), .B1 (inv_chain_out[22]), .B2 (n_39),
       .C1 (inv_chain_out[23]), .C2 (n_41), .ZN (n_64));
  AOI221_X1 g2167__4547(.A (n_59), .B1 (inv_chain_out[14]), .B2 (n_39),
       .C1 (inv_chain_out[15]), .C2 (n_41), .ZN (n_63));
  INV_X1 g2168(.A (n_61), .ZN (n_62));
  AOI221_X1 g2169__9682(.A (n_56), .B1 (inv_chain_out[20]), .B2 (n_38),
       .C1 (inv_chain_out[21]), .C2 (n_37), .ZN (n_61));
  AOI221_X1 g2170__2683(.A (n_55), .B1 (inv_chain_out[29]), .B2 (n_37),
       .C1 (inv_chain_out[30]), .C2 (n_39), .ZN (n_60));
  INV_X1 g2171(.A (n_58), .ZN (n_59));
  AOI221_X1 g2172__1309(.A (n_54), .B1 (inv_chain_out[12]), .B2 (n_38),
       .C1 (inv_chain_out[13]), .C2 (n_37), .ZN (n_58));
  AOI211_X1 g2173__6877(.A (tuning_bits[7]), .B (n_53), .C1
       (inv_chain_out[7]), .C2 (n_41), .ZN (n_57));
  OAI221_X1 g2174__2900(.A (n_49), .B1 (n_21), .B2 (n_34), .C1 (n_20),
       .C2 (n_43), .ZN (n_56));
  OAI211_X1 g2175__2391(.A (n_52), .B (n_45), .C1 (n_25), .C2 (n_34),
       .ZN (n_55));
  OAI21_X1 g2176__7675(.A (n_50), .B1 (n_26), .B2 (n_34), .ZN (n_54));
  NAND3_X1 g2177__7118(.A1 (n_51), .A2 (n_48), .A3 (n_47), .ZN (n_53));
  AOI222_X1 g2178__8757(.A1 (inv_chain_out[26]), .A2 (n_44), .B1
       (inv_chain_out[24]), .B2 (n_42), .C1 (inv_chain_out[25]), .C2
       (n_36), .ZN (n_52));
  AOI222_X1 g2179__1786(.A1 (inv_chain_out[6]), .A2 (n_39), .B1
       (inv_chain_out[5]), .B2 (n_37), .C1 (inv_chain_out[1]), .C2
       (n_36), .ZN (n_51));
  AOI222_X1 g2180__5953(.A1 (inv_chain_out[10]), .A2 (n_44), .B1
       (inv_chain_out[9]), .B2 (n_36), .C1 (inv_chain_out[8]), .C2
       (n_42), .ZN (n_50));
  AOI221_X1 g2181__5703(.A (n_24), .B1 (inv_chain_out[16]), .B2 (n_42),
       .C1 (inv_chain_out[17]), .C2 (n_36), .ZN (n_49));
  AOI22_X1 g2182__7114(.A1 (inv_chain_out[2]), .A2 (n_44), .B1
       (inv_chain_out[4]), .B2 (n_38), .ZN (n_48));
  AOI22_X1 g2183__5266(.A1 (data_in), .A2 (n_42), .B1
       (inv_chain_out[3]), .B2 (n_35), .ZN (n_47));
  NOR2_X1 g2184__2250(.A1 (n_40), .A2 (n_27), .ZN (n_46));
  NAND2_X1 g2185__6083(.A1 (inv_chain_out[28]), .A2 (n_38), .ZN (n_45));
  INV_X1 g2186(.A (n_43), .ZN (n_44));
  INV_X1 g2187(.A (n_40), .ZN (n_41));
  NAND2_X1 g2188__2703(.A1 (n_29), .A2 (tuning_bits[4]), .ZN (n_43));
  NOR2_X1 g2189__5795(.A1 (n_30), .A2 (tuning_bits[4]), .ZN (n_42));
  NAND2_X1 g2190__7344(.A1 (n_28), .A2 (tuning_bits[4]), .ZN (n_40));
  AND2_X1 g2191__1840(.A1 (n_31), .A2 (tuning_bits[4]), .ZN (n_39));
  INV_X1 g2192(.A (n_34), .ZN (n_35));
  AND2_X1 g2193__5019(.A1 (n_31), .A2 (n_22), .ZN (n_38));
  AND2_X1 g2194__1857(.A1 (n_28), .A2 (n_22), .ZN (n_37));
  NOR2_X1 g2195__9906(.A1 (n_33), .A2 (tuning_bits[4]), .ZN (n_36));
  NAND2_X1 g2196__8780(.A1 (n_32), .A2 (tuning_bits[4]), .ZN (n_34));
  INV_X1 g2197(.A (n_32), .ZN (n_33));
  NOR2_X1 g2198__4296(.A1 (n_18), .A2 (tuning_bits[5]), .ZN (n_32));
  NOR2_X1 g2199__3772(.A1 (n_23), .A2 (tuning_bits[3]), .ZN (n_31));
  INV_X1 g2200(.A (n_29), .ZN (n_30));
  NOR2_X1 g2201__1474(.A1 (tuning_bits[5]), .A2 (tuning_bits[3]), .ZN
       (n_29));
  NOR2_X1 g2202__4547(.A1 (n_18), .A2 (n_23), .ZN (n_28));
  NAND2_X1 g2203__9682(.A1 (tuning_bits[7]), .A2 (tuning_bits[6]), .ZN
       (n_27));
  INV_X1 g2204(.A (inv_chain_out[11]), .ZN (n_26));
  INV_X1 g2205(.A (inv_chain_out[27]), .ZN (n_25));
  INV_X1 g2206(.A (tuning_bits[7]), .ZN (n_24));
  INV_X1 g2207(.A (tuning_bits[5]), .ZN (n_23));
  INV_X1 g2208(.A (tuning_bits[4]), .ZN (n_22));
  INV_X1 g2209(.A (inv_chain_out[19]), .ZN (n_21));
  INV_X1 g2210(.A (inv_chain_out[18]), .ZN (n_20));
  INV_X1 g2211(.A (tuning_bits[6]), .ZN (n_19));
  INV_X1 g2212(.A (tuning_bits[3]), .ZN (n_18));
  OAI22_X1 g1639__1786(.A1 (n_1), .A2 (tuning_bits[0]), .B1 (n_5), .B2
       (n_3), .ZN (n_10));
  INV_X1 g1644(.A (inv_chain_small_out[4]), .ZN (n_5));
  INV_X1 g1645(.A (tuning_bits[2]), .ZN (n_4));
  INV_X1 g1646(.A (tuning_bits[0]), .ZN (n_3));
  INV_X1 g1648(.A (inv_chain_small_out[3]), .ZN (n_1));
  INV_X1 g177(.A (inv_chain_small_out[5]), .ZN (n_78));
  INV_X1 g175(.A (n_79), .ZN (n_80));
  NOR2_X1 g176(.A1 (n_4), .A2 (tuning_bits[0]), .ZN (n_79));
  AND2_X1 g174(.A1 (n_79), .A2 (tuning_bits[1]), .ZN (n_83));
  AND2_X1 g216(.A1 (inv_chain_small_out[6]), .A2 (n_100), .ZN (n_85));
  NAND2_X1 g393(.A1 (n_91), .A2 (n_92), .ZN (n_93));
  NAND2_X1 g399(.A1 (n_78), .A2 (n_181), .ZN (n_91));
  AOI21_X1 g394(.A (tuning_bits[1]), .B1 (n_181), .B2 (n_80), .ZN
       (n_92));
  NOR2_X1 g396(.A1 (n_94), .A2 (tuning_bits[2]), .ZN (n_95));
  NAND2_X2 g398(.A1 (inv_chain_small_out[7]), .A2 (n_83), .ZN (n_98));
  AND2_X1 g397(.A1 (n_182), .A2 (n_94), .ZN (n_100));
  INV_X1 drc_bufs2216(.A (tuning_bits[1]), .ZN (n_94));
  AOI21_X1 g51(.A (n_85), .B1 (n_10), .B2 (n_95), .ZN (n_179));
  OAI221_X1 g43(.A (n_4), .B1 (inv_chain_small_out[2]), .B2 (n_3), .C1
       (inv_chain_small_out[1]), .C2 (tuning_bits[0]), .ZN (n_181));
  NOR2_X1 g1643__2234(.A1 (n_3), .A2 (n_4), .ZN (n_182));
  NAND4_X1 g2235(.A1 (n_179), .A2 (n_93), .A3 (n_98), .A4 (n_184), .ZN
       (data_out));
  NAND2_X1 g2(.A1 (inv_chain_small_out[8]), .A2 (n_183), .ZN (n_184));
  AND2_X1 g1(.A1 (n_182), .A2 (tuning_bits[1]), .ZN (n_183));
endmodule

module invChain_LENGTH8_DRIVER_L1_31(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_32(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_33(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_34(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_35(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_36(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_37(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_38(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_39(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_40(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_41(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_42(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_43(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_44(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_45(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_46(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_47(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_48(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_49(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_50(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_51(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_52(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_53(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_54(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_55(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_56(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_57(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_58(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_59(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_60(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH8_DRIVER_L1_61(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  wire [8:0] arr_t;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (arr_t[1]));
  INV_X1 \drv1.invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X1 \drv1.invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X1 \drv1.invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X1 \drv1.invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X1 \drv1.invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X1 \drv1.invPath[6].g1 (.A (arr_t[6]), .ZN (arr_t[7]));
  INV_X1 \drv1.invPath[7].g1 (.A (arr_t[7]), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_8(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_9(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_10(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_11(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_12(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_13(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_14(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module invChain_LENGTH1_DRIVER_L1_15(in_data, out_data);
  input in_data;
  output out_data;
  wire in_data;
  wire out_data;
  INV_X1 \drv1.invPath[0].g1 (.A (in_data), .ZN (out_data));
endmodule

module TRC_TUNING_WIDTH8_TUNING_WIDTH_LOW3_1(data_in, tuning_bits,
     data_out);
  input data_in;
  input [7:0] tuning_bits;
  output data_out;
  wire data_in;
  wire [7:0] tuning_bits;
  wire data_out;
  wire [31:0] inv_chain_out;
  wire [8:0] inv_chain_small_out;
  wire mux1_out, n_0, n_1, n_5, n_6, n_9, n_10, n_11;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_212, n_213, n_219, n_220, n_221;
  wire n_222, n_223, n_225, n_227, n_238, n_240, n_241, n_243;
  invChain_LENGTH8_DRIVER_L1_31 \TRC_part_big[0].u_inv_chain8 (.in_data
       (data_in), .out_data (inv_chain_out[1]));
  invChain_LENGTH8_DRIVER_L1_32 \TRC_part_big[1].u_inv_chain8 (.in_data
       (inv_chain_out[1]), .out_data (inv_chain_out[2]));
  invChain_LENGTH8_DRIVER_L1_33 \TRC_part_big[2].u_inv_chain8 (.in_data
       (inv_chain_out[2]), .out_data (inv_chain_out[3]));
  invChain_LENGTH8_DRIVER_L1_34 \TRC_part_big[3].u_inv_chain8 (.in_data
       (inv_chain_out[3]), .out_data (inv_chain_out[4]));
  invChain_LENGTH8_DRIVER_L1_35 \TRC_part_big[4].u_inv_chain8 (.in_data
       (inv_chain_out[4]), .out_data (inv_chain_out[5]));
  invChain_LENGTH8_DRIVER_L1_36 \TRC_part_big[5].u_inv_chain8 (.in_data
       (inv_chain_out[5]), .out_data (inv_chain_out[6]));
  invChain_LENGTH8_DRIVER_L1_37 \TRC_part_big[6].u_inv_chain8 (.in_data
       (inv_chain_out[6]), .out_data (inv_chain_out[7]));
  invChain_LENGTH8_DRIVER_L1_38 \TRC_part_big[7].u_inv_chain8 (.in_data
       (inv_chain_out[7]), .out_data (inv_chain_out[8]));
  invChain_LENGTH8_DRIVER_L1_39 \TRC_part_big[8].u_inv_chain8 (.in_data
       (inv_chain_out[8]), .out_data (inv_chain_out[9]));
  invChain_LENGTH8_DRIVER_L1_40 \TRC_part_big[9].u_inv_chain8 (.in_data
       (inv_chain_out[9]), .out_data (inv_chain_out[10]));
  invChain_LENGTH8_DRIVER_L1_41 \TRC_part_big[10].u_inv_chain8
       (.in_data (inv_chain_out[10]), .out_data (inv_chain_out[11]));
  invChain_LENGTH8_DRIVER_L1_42 \TRC_part_big[11].u_inv_chain8
       (.in_data (inv_chain_out[11]), .out_data (inv_chain_out[12]));
  invChain_LENGTH8_DRIVER_L1_43 \TRC_part_big[12].u_inv_chain8
       (.in_data (inv_chain_out[12]), .out_data (inv_chain_out[13]));
  invChain_LENGTH8_DRIVER_L1_44 \TRC_part_big[13].u_inv_chain8
       (.in_data (inv_chain_out[13]), .out_data (inv_chain_out[14]));
  invChain_LENGTH8_DRIVER_L1_45 \TRC_part_big[14].u_inv_chain8
       (.in_data (inv_chain_out[14]), .out_data (inv_chain_out[15]));
  invChain_LENGTH8_DRIVER_L1_46 \TRC_part_big[15].u_inv_chain8
       (.in_data (inv_chain_out[15]), .out_data (inv_chain_out[16]));
  invChain_LENGTH8_DRIVER_L1_47 \TRC_part_big[16].u_inv_chain8
       (.in_data (inv_chain_out[16]), .out_data (inv_chain_out[17]));
  invChain_LENGTH8_DRIVER_L1_48 \TRC_part_big[17].u_inv_chain8
       (.in_data (inv_chain_out[17]), .out_data (inv_chain_out[18]));
  invChain_LENGTH8_DRIVER_L1_49 \TRC_part_big[18].u_inv_chain8
       (.in_data (inv_chain_out[18]), .out_data (inv_chain_out[19]));
  invChain_LENGTH8_DRIVER_L1_50 \TRC_part_big[19].u_inv_chain8
       (.in_data (inv_chain_out[19]), .out_data (inv_chain_out[20]));
  invChain_LENGTH8_DRIVER_L1_51 \TRC_part_big[20].u_inv_chain8
       (.in_data (inv_chain_out[20]), .out_data (inv_chain_out[21]));
  invChain_LENGTH8_DRIVER_L1_52 \TRC_part_big[21].u_inv_chain8
       (.in_data (inv_chain_out[21]), .out_data (inv_chain_out[22]));
  invChain_LENGTH8_DRIVER_L1_53 \TRC_part_big[22].u_inv_chain8
       (.in_data (inv_chain_out[22]), .out_data (inv_chain_out[23]));
  invChain_LENGTH8_DRIVER_L1_54 \TRC_part_big[23].u_inv_chain8
       (.in_data (inv_chain_out[23]), .out_data (inv_chain_out[24]));
  invChain_LENGTH8_DRIVER_L1_55 \TRC_part_big[24].u_inv_chain8
       (.in_data (inv_chain_out[24]), .out_data (inv_chain_out[25]));
  invChain_LENGTH8_DRIVER_L1_56 \TRC_part_big[25].u_inv_chain8
       (.in_data (inv_chain_out[25]), .out_data (inv_chain_out[26]));
  invChain_LENGTH8_DRIVER_L1_57 \TRC_part_big[26].u_inv_chain8
       (.in_data (inv_chain_out[26]), .out_data (inv_chain_out[27]));
  invChain_LENGTH8_DRIVER_L1_58 \TRC_part_big[27].u_inv_chain8
       (.in_data (inv_chain_out[27]), .out_data (inv_chain_out[28]));
  invChain_LENGTH8_DRIVER_L1_59 \TRC_part_big[28].u_inv_chain8
       (.in_data (inv_chain_out[28]), .out_data (inv_chain_out[29]));
  invChain_LENGTH8_DRIVER_L1_60 \TRC_part_big[29].u_inv_chain8
       (.in_data (inv_chain_out[29]), .out_data (inv_chain_out[30]));
  invChain_LENGTH8_DRIVER_L1_61 \TRC_part_big[30].u_inv_chain8
       (.in_data (inv_chain_out[30]), .out_data (inv_chain_out[31]));
  invChain_LENGTH1_DRIVER_L1_8 \TRC_part_small[0].u_inv_chain1
       (.in_data (mux1_out), .out_data (inv_chain_small_out[1]));
  invChain_LENGTH1_DRIVER_L1_9 \TRC_part_small[1].u_inv_chain1
       (.in_data (inv_chain_small_out[1]), .out_data
       (inv_chain_small_out[2]));
  invChain_LENGTH1_DRIVER_L1_10 \TRC_part_small[2].u_inv_chain1
       (.in_data (inv_chain_small_out[2]), .out_data
       (inv_chain_small_out[3]));
  invChain_LENGTH1_DRIVER_L1_11 \TRC_part_small[3].u_inv_chain1
       (.in_data (inv_chain_small_out[3]), .out_data
       (inv_chain_small_out[4]));
  invChain_LENGTH1_DRIVER_L1_12 \TRC_part_small[4].u_inv_chain1
       (.in_data (inv_chain_small_out[4]), .out_data
       (inv_chain_small_out[5]));
  invChain_LENGTH1_DRIVER_L1_13 \TRC_part_small[5].u_inv_chain1
       (.in_data (inv_chain_small_out[5]), .out_data
       (inv_chain_small_out[6]));
  invChain_LENGTH1_DRIVER_L1_14 \TRC_part_small[6].u_inv_chain1
       (.in_data (inv_chain_small_out[6]), .out_data
       (inv_chain_small_out[7]));
  invChain_LENGTH1_DRIVER_L1_15 \TRC_part_small[7].u_inv_chain1
       (.in_data (inv_chain_small_out[7]), .out_data
       (inv_chain_small_out[8]));
  INV_X1 g2161(.A (n_68), .ZN (mux1_out));
  AOI21_X1 g2162__5266(.A (n_67), .B1 (inv_chain_out[31]), .B2 (n_46),
       .ZN (n_68));
  OAI21_X2 g2163__2250(.A (n_66), .B1 (n_60), .B2 (n_27), .ZN (n_67));
  INV_X1 g2164(.A (n_65), .ZN (n_66));
  OAI33_X1 g2165__6083(.A1 (n_64), .A2 (n_57), .A3 (tuning_bits[6]),
       .B1 (n_63), .B2 (n_19), .B3 (tuning_bits[7]), .ZN (n_65));
  AOI221_X1 g2166__2703(.A (n_62), .B1 (inv_chain_out[22]), .B2 (n_39),
       .C1 (inv_chain_out[23]), .C2 (n_41), .ZN (n_64));
  AOI221_X1 g2167__5795(.A (n_59), .B1 (inv_chain_out[14]), .B2 (n_39),
       .C1 (inv_chain_out[15]), .C2 (n_41), .ZN (n_63));
  INV_X1 g2168(.A (n_61), .ZN (n_62));
  AOI221_X1 g2169__7344(.A (n_56), .B1 (inv_chain_out[20]), .B2 (n_38),
       .C1 (inv_chain_out[21]), .C2 (n_37), .ZN (n_61));
  AOI221_X1 g2170__1840(.A (n_55), .B1 (inv_chain_out[29]), .B2 (n_37),
       .C1 (inv_chain_out[30]), .C2 (n_39), .ZN (n_60));
  INV_X1 g2171(.A (n_58), .ZN (n_59));
  AOI221_X1 g2172__5019(.A (n_54), .B1 (inv_chain_out[12]), .B2 (n_38),
       .C1 (inv_chain_out[13]), .C2 (n_37), .ZN (n_58));
  AOI211_X1 g2173__1857(.A (tuning_bits[7]), .B (n_53), .C1
       (inv_chain_out[7]), .C2 (n_41), .ZN (n_57));
  OAI221_X1 g2174__9906(.A (n_49), .B1 (n_21), .B2 (n_34), .C1 (n_20),
       .C2 (n_43), .ZN (n_56));
  OAI211_X1 g2175__8780(.A (n_52), .B (n_45), .C1 (n_25), .C2 (n_34),
       .ZN (n_55));
  OAI21_X1 g2176__4296(.A (n_50), .B1 (n_26), .B2 (n_34), .ZN (n_54));
  NAND3_X1 g2177__3772(.A1 (n_51), .A2 (n_48), .A3 (n_47), .ZN (n_53));
  AOI222_X1 g2178__1474(.A1 (inv_chain_out[26]), .A2 (n_44), .B1
       (inv_chain_out[24]), .B2 (n_42), .C1 (inv_chain_out[25]), .C2
       (n_36), .ZN (n_52));
  AOI222_X1 g2179__4547(.A1 (inv_chain_out[6]), .A2 (n_39), .B1
       (inv_chain_out[5]), .B2 (n_37), .C1 (inv_chain_out[1]), .C2
       (n_36), .ZN (n_51));
  AOI222_X1 g2180__9682(.A1 (inv_chain_out[10]), .A2 (n_44), .B1
       (inv_chain_out[9]), .B2 (n_36), .C1 (inv_chain_out[8]), .C2
       (n_42), .ZN (n_50));
  AOI221_X1 g2181__2683(.A (n_24), .B1 (inv_chain_out[16]), .B2 (n_42),
       .C1 (inv_chain_out[17]), .C2 (n_36), .ZN (n_49));
  AOI22_X1 g2182__1309(.A1 (inv_chain_out[2]), .A2 (n_44), .B1
       (inv_chain_out[4]), .B2 (n_38), .ZN (n_48));
  AOI22_X1 g2183__6877(.A1 (data_in), .A2 (n_42), .B1
       (inv_chain_out[3]), .B2 (n_35), .ZN (n_47));
  NOR2_X1 g2184__2900(.A1 (n_40), .A2 (n_27), .ZN (n_46));
  NAND2_X1 g2185__2391(.A1 (inv_chain_out[28]), .A2 (n_38), .ZN (n_45));
  INV_X1 g2186(.A (n_43), .ZN (n_44));
  INV_X1 g2187(.A (n_40), .ZN (n_41));
  NAND2_X1 g2188__7675(.A1 (n_29), .A2 (tuning_bits[4]), .ZN (n_43));
  NOR2_X1 g2189__7118(.A1 (n_30), .A2 (tuning_bits[4]), .ZN (n_42));
  NAND2_X1 g2190__8757(.A1 (n_28), .A2 (tuning_bits[4]), .ZN (n_40));
  AND2_X1 g2191__1786(.A1 (n_31), .A2 (tuning_bits[4]), .ZN (n_39));
  INV_X1 g2192(.A (n_34), .ZN (n_35));
  AND2_X1 g2193__5953(.A1 (n_31), .A2 (n_22), .ZN (n_38));
  AND2_X1 g2194__5703(.A1 (n_28), .A2 (n_22), .ZN (n_37));
  NOR2_X1 g2195__7114(.A1 (n_33), .A2 (tuning_bits[4]), .ZN (n_36));
  NAND2_X1 g2196__5266(.A1 (n_32), .A2 (tuning_bits[4]), .ZN (n_34));
  INV_X1 g2197(.A (n_32), .ZN (n_33));
  NOR2_X1 g2198__2250(.A1 (n_18), .A2 (tuning_bits[5]), .ZN (n_32));
  NOR2_X1 g2199__6083(.A1 (n_23), .A2 (tuning_bits[3]), .ZN (n_31));
  INV_X1 g2200(.A (n_29), .ZN (n_30));
  NOR2_X1 g2201__2703(.A1 (tuning_bits[5]), .A2 (tuning_bits[3]), .ZN
       (n_29));
  NOR2_X1 g2202__5795(.A1 (n_18), .A2 (n_23), .ZN (n_28));
  NAND2_X1 g2203__7344(.A1 (tuning_bits[7]), .A2 (tuning_bits[6]), .ZN
       (n_27));
  INV_X1 g2204(.A (inv_chain_out[11]), .ZN (n_26));
  INV_X1 g2205(.A (inv_chain_out[27]), .ZN (n_25));
  INV_X1 g2206(.A (tuning_bits[7]), .ZN (n_24));
  INV_X1 g2207(.A (tuning_bits[5]), .ZN (n_23));
  INV_X1 g2208(.A (tuning_bits[4]), .ZN (n_22));
  INV_X1 g2209(.A (inv_chain_out[19]), .ZN (n_21));
  INV_X1 g2210(.A (inv_chain_out[18]), .ZN (n_20));
  INV_X1 g2211(.A (tuning_bits[6]), .ZN (n_19));
  INV_X1 g2212(.A (tuning_bits[3]), .ZN (n_18));
  AND2_X1 g1638__1474(.A1 (n_6), .A2 (n_0), .ZN (n_11));
  OAI22_X1 g1639__4547(.A1 (n_1), .A2 (tuning_bits[0]), .B1 (n_5), .B2
       (n_213), .ZN (n_10));
  NOR2_X1 g1640__9682(.A1 (n_0), .A2 (tuning_bits[2]), .ZN (n_9));
  NOR2_X1 g1643__1309(.A1 (n_213), .A2 (n_212), .ZN (n_6));
  INV_X1 g1644(.A (inv_chain_small_out[4]), .ZN (n_5));
  INV_X1 g1648(.A (inv_chain_small_out[3]), .ZN (n_1));
  INV_X1 g66(.A (tuning_bits[2]), .ZN (n_212));
  INV_X1 g65(.A (tuning_bits[0]), .ZN (n_213));
  OAI21_X1 g171(.A (n_219), .B1 (n_220), .B2 (n_222), .ZN (n_223));
  OAI221_X1 g173(.A (n_212), .B1 (inv_chain_small_out[1]), .B2
       (tuning_bits[0]), .C1 (inv_chain_small_out[2]), .C2 (n_213), .ZN
       (n_219));
  INV_X1 g177(.A (inv_chain_small_out[5]), .ZN (n_220));
  INV_X1 g175(.A (n_221), .ZN (n_222));
  NOR2_X1 g176(.A1 (n_212), .A2 (tuning_bits[0]), .ZN (n_221));
  AND2_X1 g174(.A1 (n_221), .A2 (tuning_bits[1]), .ZN (n_225));
  AND2_X1 g216(.A1 (inv_chain_small_out[6]), .A2 (n_11), .ZN (n_227));
  NAND2_X1 g136(.A1 (n_223), .A2 (n_0), .ZN (n_238));
  NAND3_X1 g134(.A1 (inv_chain_small_out[8]), .A2 (n_6), .A3
       (tuning_bits[1]), .ZN (n_240));
  NAND2_X1 g135(.A1 (inv_chain_small_out[7]), .A2 (n_225), .ZN (n_241));
  NAND4_X1 g46(.A1 (n_243), .A2 (n_238), .A3 (n_241), .A4 (n_240), .ZN
       (data_out));
  AOI21_X1 g47(.A (n_227), .B1 (n_10), .B2 (n_9), .ZN (n_243));
  INV_X1 drc_bufs2220(.A (tuning_bits[1]), .ZN (n_0));
endmodule

module checker(data_in1, data_in0, ref_in1, last_bit, is_error);
  input data_in1, data_in0, ref_in1, last_bit;
  output is_error;
  wire data_in1, data_in0, ref_in1, last_bit;
  wire is_error;
  wire n_0, n_1, n_2, n_3;
  OAI21_X1 g69__6877(.A (n_3), .B1 (n_1), .B2 (last_bit), .ZN
       (is_error));
  INV_X1 g70(.A (n_2), .ZN (n_3));
  MUX2_X1 g71__2900(.A (n_1), .B (last_bit), .S (n_0), .Z (n_2));
  XNOR2_X1 g72__2391(.A (ref_in1), .B (data_in0), .ZN (n_1));
  XOR2_X1 g73__7675(.A (ref_in1), .B (data_in1), .Z (n_0));
endmodule

module DVM(clk, rst_n, tuning_bits, is_error);
  input clk, rst_n;
  input [7:0] tuning_bits;
  output is_error;
  wire clk, rst_n;
  wire [7:0] tuning_bits;
  wire is_error;
  wire D_out_synced1, D_out_synced2, T_FF, UNCONNECTED, UNCONNECTED0,
       UNCONNECTED1, UNCONNECTED2, checker_out;
  wire data_out0, data_out1, n_0, n_1, n_2, n_3, n_16, n_22;
  wire n_27, n_32, n_55, n_60, n_65, n_70, n_78, n_166;
  wire n_239, n_311, n_313, n_392, trc_in0, trc_out0;
  TRC_TUNING_WIDTH8_TUNING_WIDTH_LOW3 u_TRC_0(.data_in (n_311),
       .tuning_bits ({n_32, n_65, n_55, n_22, n_60, n_70, n_166,
       n_27}), .data_out (data_out0));
  TRC_TUNING_WIDTH8_TUNING_WIDTH_LOW3_1 u_TRC_1(.data_in (n_392),
       .tuning_bits ({n_32, n_65, n_55, n_22, n_60, n_70, n_166,
       n_27}), .data_out (data_out1));
  checker u_checker(.data_in1 (n_313), .data_in0 (trc_out0), .ref_in1
       (D_out_synced2), .last_bit (n_27), .is_error (checker_out));
  DFF_X1 T_FF_reg(.CK (clk), .D (n_3), .Q (T_FF), .QN (n_16));
  AND2_X1 g16__7118(.A1 (n_16), .A2 (n_78), .ZN (n_3));
  DFF_X1 is_error_reg(.CK (clk), .D (n_0), .Q (is_error), .QN
       (UNCONNECTED));
  DFF_X1 D_out_synced2_reg(.CK (clk), .D (D_out_synced1), .Q
       (D_out_synced2), .QN (UNCONNECTED0));
  DFF_X1 trc_in0_reg(.CK (clk), .D (T_FF), .Q (trc_in0), .QN (n_1));
  DFF_X1 D_out_synced1_reg(.CK (clk), .D (n_16), .Q (D_out_synced1),
       .QN (n_2));
  DFF_X1 trc_out0_reg(.CK (clk), .D (data_out0), .Q (trc_out0), .QN
       (UNCONNECTED1));
  AND2_X1 g21__8757(.A1 (checker_out), .A2 (n_78), .ZN (n_0));
  CLKBUF_X1 drc_buf_sp(.A (rst_n), .Z (n_78));
  BUF_X1 drc_buf_sp168(.A (tuning_bits[0]), .Z (n_27));
  CLKBUF_X1 drc_buf_sp171(.A (tuning_bits[7]), .Z (n_32));
  CLKBUF_X1 drc_buf_sp174(.A (tuning_bits[2]), .Z (n_70));
  CLKBUF_X1 drc_buf_sp177(.A (tuning_bits[3]), .Z (n_60));
  CLKBUF_X1 drc_buf_sp180(.A (tuning_bits[4]), .Z (n_22));
  CLKBUF_X1 drc_buf_sp183(.A (tuning_bits[5]), .Z (n_55));
  CLKBUF_X1 drc_buf_sp186(.A (tuning_bits[6]), .Z (n_65));
  INV_X1 drc_bufs201(.A (n_239), .ZN (n_166));
  INV_X1 drc_bufs202(.A (tuning_bits[1]), .ZN (n_239));
  INV_X2 g9(.A (n_1), .ZN (n_311));
  DFFS_X1 trc_out1_reg(.SN (1'b1), .CK (clk), .D (data_out1), .Q
       (n_313), .QN (UNCONNECTED2));
  INV_X2 g287(.A (n_2), .ZN (n_392));
endmodule

