
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Oct 22 2025 23:21:20 CDT (Oct 23 2025 04:21:20 UTC)

// Verification Directory fv/stageUnit 

module stageUnit(in_data, out_data);
  input [31:0] in_data;
  output out_data;
  wire [31:0] in_data;
  wire out_data;
  wire [7:0] arr_t;
  INV_X8 \invPath[0].g1 (.A (in_data[0]), .ZN (arr_t[1]));
  INV_X8 \invPath[1].g1 (.A (arr_t[1]), .ZN (arr_t[2]));
  INV_X8 \invPath[2].g1 (.A (arr_t[2]), .ZN (arr_t[3]));
  INV_X8 \invPath[3].g1 (.A (arr_t[3]), .ZN (arr_t[4]));
  INV_X8 \invPath[4].g1 (.A (arr_t[4]), .ZN (arr_t[5]));
  INV_X8 \invPath[5].g1 (.A (arr_t[5]), .ZN (arr_t[6]));
  INV_X8 \invPath[6].g1 (.A (arr_t[6]), .ZN (out_data));
endmodule

