
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Oct 23 2025 22:34:39 CDT (Oct 24 2025 03:34:39 UTC)

// Verification Directory fv/muxInvChain 

module muxInvChain(in_data, in_data_b, in_ctrl, out_data);
  input in_data, in_data_b, in_ctrl;
  output out_data;
  wire in_data, in_data_b, in_ctrl;
  wire out_data;
  wire \drv1.muxInvPath[0].t , \drv1.muxInvPath[1].t ,
       \drv1.muxInvPath[2].t , \drv1.muxInvPath[3].t , n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_9, n_17, n_25;
  INV_X1 \drv1.muxInvPath[0].g1 (.A (n_25), .ZN (\drv1.muxInvPath[0].t
       ));
  INV_X1 \drv1.muxInvPath[1].g1 (.A (n_0), .ZN (\drv1.muxInvPath[1].t
       ));
  INV_X1 \drv1.muxInvPath[2].g1 (.A (n_3), .ZN (\drv1.muxInvPath[2].t
       ));
  INV_X1 \drv1.muxInvPath[3].g1 (.A (n_4), .ZN (\drv1.muxInvPath[3].t
       ));
  INV_X1 g131(.A (n_5), .ZN (out_data));
  AOI21_X1 g132(.A (n_1), .B1 (\drv1.muxInvPath[3].t ), .B2 (n_9), .ZN
       (n_5));
  MUX2_X1 g133(.A (\drv1.muxInvPath[2].t ), .B (n_17), .S (n_9), .Z
       (n_4));
  INV_X1 g134(.A (n_2), .ZN (n_3));
  AOI21_X1 g135(.A (n_1), .B1 (\drv1.muxInvPath[1].t ), .B2 (n_9), .ZN
       (n_2));
  MUX2_X1 g136(.A (\drv1.muxInvPath[0].t ), .B (n_17), .S (n_9), .Z
       (n_0));
  NOR2_X1 g137(.A1 (n_17), .A2 (n_9), .ZN (n_1));
  CLKBUF_X1 drc_buf_sp(.A (in_data), .Z (n_25));
  CLKBUF_X1 drc_buf_sp164(.A (in_data_b), .Z (n_17));
  CLKBUF_X1 drc_buf_sp173(.A (in_ctrl), .Z (n_9));
endmodule

