
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Oct 23 2025 16:51:47 CDT (Oct 23 2025 21:51:47 UTC)

// Verification Directory fv/nandChain 

module nandChain(in_data, in_ctrl, out_data);
  input in_data, in_ctrl;
  output out_data;
  wire in_data, in_ctrl;
  wire out_data;
  wire [8:0] arr_t;
  wire n_0, n_3, n_6;
  NAND2_X4 \drv4.nandPath[0].g1 (.A1 (n_6), .A2 (n_3), .ZN (arr_t[1]));
  NAND2_X4 \drv4.nandPath[1].g1 (.A1 (arr_t[1]), .A2 (n_0), .ZN
       (arr_t[2]));
  NAND2_X4 \drv4.nandPath[2].g1 (.A1 (arr_t[2]), .A2 (n_3), .ZN
       (arr_t[3]));
  NAND2_X4 \drv4.nandPath[3].g1 (.A1 (arr_t[3]), .A2 (n_0), .ZN
       (arr_t[4]));
  NAND2_X4 \drv4.nandPath[4].g1 (.A1 (arr_t[4]), .A2 (n_3), .ZN
       (arr_t[5]));
  NAND2_X4 \drv4.nandPath[5].g1 (.A1 (arr_t[5]), .A2 (n_0), .ZN
       (arr_t[6]));
  NAND2_X4 \drv4.nandPath[6].g1 (.A1 (arr_t[6]), .A2 (n_3), .ZN
       (arr_t[7]));
  NAND2_X4 \drv4.nandPath[7].g1 (.A1 (arr_t[7]), .A2 (n_0), .ZN
       (out_data));
  CLKBUF_X1 drc_buf_sp(.A (in_data), .Z (n_6));
  INV_X1 drc_bufs15(.A (n_3), .ZN (n_0));
  CLKBUF_X1 drc_buf_sp25(.A (in_ctrl), .Z (n_3));
endmodule

