
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Oct 23 2025 23:06:15 CDT (Oct 24 2025 04:06:15 UTC)

// Verification Directory fv/nandNorChain 

module nandNorChain(in_data, in_data_b, out_data);
  input in_data, in_data_b;
  output out_data;
  wire in_data, in_data_b;
  wire out_data;
  wire [4:0] arr_t;
  wire \drv1.nandNorPath[0].t , \drv1.nandNorPath[1].t ,
       \drv1.nandNorPath[2].t , \drv1.nandNorPath[3].t , n_0, n_3, n_6;
  NAND2_X1 \drv1.nandNorPath[0].ut_nand (.A1 (n_6), .A2 (n_3), .ZN
       (\drv1.nandNorPath[0].t ));
  NOR2_X1 \drv1.nandNorPath[0].ut_nor (.A1 (\drv1.nandNorPath[0].t ),
       .A2 (n_0), .ZN (arr_t[1]));
  NAND2_X1 \drv1.nandNorPath[1].ut_nand (.A1 (arr_t[1]), .A2 (n_3), .ZN
       (\drv1.nandNorPath[1].t ));
  NOR2_X1 \drv1.nandNorPath[1].ut_nor (.A1 (\drv1.nandNorPath[1].t ),
       .A2 (n_0), .ZN (arr_t[2]));
  NAND2_X1 \drv1.nandNorPath[2].ut_nand (.A1 (arr_t[2]), .A2 (n_3), .ZN
       (\drv1.nandNorPath[2].t ));
  NOR2_X1 \drv1.nandNorPath[2].ut_nor (.A1 (\drv1.nandNorPath[2].t ),
       .A2 (n_0), .ZN (arr_t[3]));
  NAND2_X1 \drv1.nandNorPath[3].ut_nand (.A1 (arr_t[3]), .A2 (n_3), .ZN
       (\drv1.nandNorPath[3].t ));
  NOR2_X1 \drv1.nandNorPath[3].ut_nor (.A1 (\drv1.nandNorPath[3].t ),
       .A2 (n_0), .ZN (out_data));
  CLKBUF_X1 drc_buf_sp(.A (in_data), .Z (n_6));
  INV_X1 drc_bufs15(.A (n_3), .ZN (n_0));
  CLKBUF_X1 drc_buf_sp25(.A (in_data_b), .Z (n_3));
endmodule

