
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov  1 2025 20:54:31 CDT (Nov  2 2025 01:54:31 UTC)

// Verification Directory fv/TRC 

module TRC(data_in, tuning_bits, data_out);
  input data_in;
  input [7:0] tuning_bits;
  output data_out;
  wire data_in;
  wire [7:0] tuning_bits;
  wire data_out;
  wire [8:0] \TRC_part_big[0].u_inv_chain8_arr_t ;
  wire [31:0] inv_chain_out;
  wire [8:0] \TRC_part_big[1].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[2].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[3].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[4].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[5].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[6].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[7].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[8].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[9].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[10].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[11].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[12].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[13].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[14].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[15].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[16].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[17].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[18].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[19].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[20].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[21].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[22].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[23].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[24].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[25].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[26].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[27].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[28].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[29].u_inv_chain8_arr_t ;
  wire [8:0] \TRC_part_big[30].u_inv_chain8_arr_t ;
  wire [8:0] inv_chain_small_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_51;
  wire n_52, n_53, n_54, n_55, n_67, n_70, n_97;
  OR2_X1 g415__8780(.A1 (n_48), .A2 (n_52), .ZN (data_out));
  AOI21_X1 g416__4296(.A (tuning_bits[1]), .B1 (n_47), .B2 (n_54), .ZN
       (n_48));
  NAND2_X1 g417__3772(.A1 (n_67), .A2 (tuning_bits[2]), .ZN (n_47));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[0].g1 (.A (n_70),
       .ZN (\TRC_part_big[0].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[0].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[0].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[0].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[1]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[1]), .ZN (\TRC_part_big[1].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[1].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[1].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[1].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[2]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[2]), .ZN (\TRC_part_big[2].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[2].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[2].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[2].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[3]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[3]), .ZN (\TRC_part_big[3].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[3].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[3].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[3].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[4]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[4]), .ZN (\TRC_part_big[4].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[4].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[4].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[4].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[5]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[5]), .ZN (\TRC_part_big[5].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[5].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[5].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[5].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[6]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[6]), .ZN (\TRC_part_big[6].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[6].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[6].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[6].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[7]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[7]), .ZN (\TRC_part_big[7].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[7].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[7].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[7].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[8]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[8]), .ZN (\TRC_part_big[8].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[8].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[8].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[8].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[9]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[9]), .ZN (\TRC_part_big[9].u_inv_chain8_arr_t
       [1]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[9].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[9].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[9].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[10]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[10]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[10].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[10].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[10].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[11]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[11]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[11].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[11].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[11].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[12]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[12]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[12].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[12].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[12].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[13]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[13]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[13].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[13].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[13].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[14]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[14]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[14].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[14].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[14].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[15]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[15]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[15].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[15].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[15].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[16]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[16]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[16].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[16].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[16].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[17]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[17]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[17].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[17].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[17].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[18]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[18]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[18].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[18].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[18].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[19]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[19]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[19].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[19].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[19].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[20]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[20]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[20].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[20].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[20].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[21]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[21]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[21].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[21].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[21].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[22]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[22]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[22].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[22].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[22].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[23]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[23]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[23].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[23].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[23].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[24]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[24]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[24].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[24].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[24].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[25]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[25]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[25].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[25].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[25].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[26]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[26]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[26].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[26].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[26].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[27]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[27]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[27].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[27].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[27].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[28]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[28]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[28].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[28].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[28].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[29]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[29]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[29].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[29].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[29].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[30]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[0].g1 (.A
       (inv_chain_out[30]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [1]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[1].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [1]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [2]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[2].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [2]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [3]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[3].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [3]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [4]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[4].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [4]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [5]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[5].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [5]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [6]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[6].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [6]), .ZN
       (\TRC_part_big[30].u_inv_chain8_arr_t [7]));
  INV_X1 \TRC_part_big[30].u_inv_chain8_drv1.invPath[7].g1 (.A
       (\TRC_part_big[30].u_inv_chain8_arr_t [7]), .ZN
       (inv_chain_out[31]));
  OAI21_X1 g500__4547(.A (n_45), .B1 (n_44), .B2 (n_43), .ZN (n_52));
  NAND3_X1 g502__9682(.A1 (n_42), .A2 (tuning_bits[0]), .A3 (n_41), .ZN
       (n_45));
  NAND3_X1 g503__2683(.A1 (inv_chain_small_out[1]), .A2 (n_40), .A3
       (n_41), .ZN (n_54));
  AND3_X1 g504__1309(.A1 (inv_chain_small_out[3]), .A2 (n_40), .A3
       (n_41), .ZN (n_39));
  INV_X1 g508(.A (tuning_bits[2]), .ZN (n_41));
  INV_X1 g509(.A (tuning_bits[0]), .ZN (n_40));
  INV_X1 g510(.A (tuning_bits[1]), .ZN (n_43));
  AOI21_X1 g501__2900(.A (n_39), .B1 (n_38), .B2 (tuning_bits[2]), .ZN
       (n_44));
  MUX2_X1 g506__2391(.A (inv_chain_small_out[2]), .B
       (inv_chain_small_out[4]), .S (tuning_bits[1]), .Z (n_42));
  MUX2_X1 g505__7675(.A (inv_chain_small_out[7]), .B
       (inv_chain_small_out[8]), .S (tuning_bits[0]), .Z (n_38));
  INV_X1 \TRC_part_small[0].u_inv_chain1_drv1.invPath[0].g1 (.A (n_37),
       .ZN (inv_chain_small_out[1]));
  INV_X1 \TRC_part_small[1].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[1]), .ZN (inv_chain_small_out[2]));
  INV_X1 \TRC_part_small[2].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[2]), .ZN (inv_chain_small_out[3]));
  INV_X1 \TRC_part_small[3].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[3]), .ZN (inv_chain_small_out[4]));
  INV_X1 \TRC_part_small[4].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[4]), .ZN (inv_chain_small_out[5]));
  INV_X1 \TRC_part_small[5].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[5]), .ZN (inv_chain_small_out[6]));
  INV_X1 \TRC_part_small[6].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[6]), .ZN (inv_chain_small_out[7]));
  INV_X1 \TRC_part_small[7].u_inv_chain1_drv1.invPath[0].g1 (.A
       (inv_chain_small_out[7]), .ZN (inv_chain_small_out[8]));
  OAI21_X1 g429__8757(.A (n_51), .B1 (n_36), .B2 (tuning_bits[6]), .ZN
       (n_37));
  INV_X1 g430(.A (n_35), .ZN (n_36));
  OAI21_X1 g431__1786(.A (n_53), .B1 (n_34), .B2 (tuning_bits[7]), .ZN
       (n_35));
  AOI21_X1 g432__5953(.A (n_55), .B1 (inv_chain_out[3]), .B2 (n_97),
       .ZN (n_34));
  OAI221_X1 g1139__5703(.A (tuning_bits[6]), .B1 (n_33), .B2 (n_32),
       .C1 (n_31), .C2 (tuning_bits[7]), .ZN (n_51));
  NAND2_X1 g1140__7114(.A1 (n_30), .A2 (tuning_bits[7]), .ZN (n_53));
  NAND3_X1 g1144__5266(.A1 (n_29), .A2 (n_28), .A3 (n_27), .ZN (n_55));
  AOI222_X1 g1145__2250(.A1 (n_70), .A2 (n_26), .B1 (inv_chain_out[5]),
       .B2 (n_25), .C1 (inv_chain_out[6]), .C2 (n_24), .ZN (n_29));
  AOI22_X1 g1146__6083(.A1 (inv_chain_out[18]), .A2 (n_23), .B1
       (inv_chain_out[21]), .B2 (n_25), .ZN (n_22));
  AOI22_X1 g1147__2703(.A1 (inv_chain_out[16]), .A2 (n_26), .B1
       (inv_chain_out[17]), .B2 (n_21), .ZN (n_20));
  AOI22_X1 g1148__5795(.A1 (inv_chain_out[24]), .A2 (n_26), .B1
       (inv_chain_out[25]), .B2 (n_21), .ZN (n_19));
  AOI22_X1 g1151__7344(.A1 (inv_chain_out[22]), .A2 (n_24), .B1
       (inv_chain_out[23]), .B2 (n_18), .ZN (n_17));
  AOI22_X1 g1152__1840(.A1 (inv_chain_out[26]), .A2 (n_23), .B1
       (inv_chain_out[29]), .B2 (n_25), .ZN (n_16));
  AOI22_X1 g1153__5019(.A1 (inv_chain_out[8]), .A2 (n_26), .B1
       (inv_chain_out[9]), .B2 (n_21), .ZN (n_15));
  AOI22_X1 g1154__1857(.A1 (inv_chain_out[30]), .A2 (n_24), .B1
       (inv_chain_out[31]), .B2 (n_18), .ZN (n_14));
  AOI22_X1 g1155__9906(.A1 (inv_chain_out[2]), .A2 (n_23), .B1
       (inv_chain_out[7]), .B2 (n_18), .ZN (n_28));
  AOI22_X1 g1156__8780(.A1 (inv_chain_out[14]), .A2 (n_24), .B1
       (inv_chain_out[15]), .B2 (n_18), .ZN (n_13));
  AOI22_X1 g1157__4296(.A1 (inv_chain_out[4]), .A2 (n_12), .B1
       (inv_chain_out[1]), .B2 (n_21), .ZN (n_27));
  AOI22_X1 g1159__3772(.A1 (inv_chain_out[10]), .A2 (n_23), .B1
       (inv_chain_out[13]), .B2 (n_25), .ZN (n_11));
  AND2_X1 g1161__1474(.A1 (tuning_bits[4]), .A2 (n_9), .ZN (n_24));
  NOR2_X1 g1162__4547(.A1 (n_8), .A2 (n_7), .ZN (n_18));
  NOR2_X1 g1163__9682(.A1 (tuning_bits[4]), .A2 (n_6), .ZN (n_26));
  AND2_X1 g1165__1309(.A1 (n_8), .A2 (n_5), .ZN (n_21));
  NOR2_X1 g1166__6877(.A1 (n_8), .A2 (n_6), .ZN (n_23));
  NOR2_X1 g1167__2900(.A1 (tuning_bits[4]), .A2 (n_7), .ZN (n_25));
  AND2_X1 g1168__2391(.A1 (n_8), .A2 (n_9), .ZN (n_12));
  NOR2_X1 g1169__7675(.A1 (n_4), .A2 (tuning_bits[3]), .ZN (n_9));
  NOR2_X1 g1170__7118(.A1 (n_3), .A2 (tuning_bits[5]), .ZN (n_5));
  NAND2_X1 g1171__8757(.A1 (n_4), .A2 (n_3), .ZN (n_6));
  NAND2_X1 g1172__1786(.A1 (tuning_bits[5]), .A2 (tuning_bits[3]), .ZN
       (n_7));
  INV_X1 g1173(.A (tuning_bits[7]), .ZN (n_32));
  INV_X1 g1174(.A (tuning_bits[3]), .ZN (n_3));
  INV_X1 g1175(.A (tuning_bits[5]), .ZN (n_4));
  INV_X1 g1176(.A (tuning_bits[4]), .ZN (n_8));
  NAND4_X1 g1141__5953(.A1 (n_2), .A2 (n_19), .A3 (n_14), .A4 (n_16),
       .ZN (n_33));
  NAND4_X1 g1143__5703(.A1 (n_1), .A2 (n_11), .A3 (n_13), .A4 (n_15),
       .ZN (n_31));
  NAND4_X1 g1142__7114(.A1 (n_0), .A2 (n_20), .A3 (n_17), .A4 (n_22),
       .ZN (n_30));
  AOI22_X1 g1150__5266(.A1 (inv_chain_out[28]), .A2 (n_12), .B1
       (inv_chain_out[27]), .B2 (n_97), .ZN (n_2));
  AOI22_X1 g1158__2250(.A1 (inv_chain_out[12]), .A2 (n_12), .B1
       (inv_chain_out[11]), .B2 (n_97), .ZN (n_1));
  AOI22_X1 g1149__6083(.A1 (inv_chain_out[20]), .A2 (n_12), .B1
       (inv_chain_out[19]), .B2 (n_97), .ZN (n_0));
  MUX2_X1 g2(.A (inv_chain_small_out[5]), .B (inv_chain_small_out[6]),
       .S (tuning_bits[0]), .Z (n_67));
  CLKBUF_X1 drc_buf_sp(.A (data_in), .Z (n_70));
  AND2_X1 g1198(.A1 (tuning_bits[4]), .A2 (n_5), .ZN (n_97));
endmodule

