
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Oct 26 2025 21:08:44 CDT (Oct 27 2025 02:08:44 UTC)

// Verification Directory fv/tunable_delay 
`timescale 1ns/1ps

module transistor_segment(din, dout);
  input din;
  output dout;
  wire din;
  wire dout;
  wire mid;
  INV_X1 u_inv0(.A (din), .ZN (mid));
  INV_X1 u_inv1(.A (mid), .ZN (dout));
endmodule

module wire_segment(din, dout);
  input din;
  output dout;
  wire din;
  wire dout;
  wire w_mid;
  BUF_X1 u_buf_in(.A (din), .Z (w_mid));
  BUF_X1 u_buf_out(.A (w_mid), .Z (dout));
endmodule

module tunable_delay(clk_in, tuning_bits, clk_out);
  input clk_in;
  input [4:0] tuning_bits;
  output clk_out;
  wire clk_in;
  wire [4:0] tuning_bits;
  wire clk_out;
  wire [15:1] t_tap;
  wire TDB_tap1, TDB_tap2, TDB_tap3, TDB_tap5, TDB_tap6, TDB_tap7,
       TDB_tap8, TDB_tap9;
  wire TDB_tap10, TDB_tap11, TDB_tap13, TDB_tap14, TDB_tap15,
       WDB_long_mid0, WDB_long_mid1, WDB_med_mid;
  wire WDB_short_out, n_0, n_1, w_tap_b, w_tap_c;
  transistor_segment TDB_s0(.din (clk_in), .dout (TDB_tap1));
  transistor_segment TDB_s1(.din (TDB_tap1), .dout (TDB_tap2));
  transistor_segment TDB_s2(.din (TDB_tap2), .dout (TDB_tap3));
  transistor_segment TDB_s3(.din (TDB_tap3), .dout (t_tap[4]));
  transistor_segment TDB_s4(.din (t_tap[4]), .dout (TDB_tap5));
  transistor_segment TDB_s5(.din (TDB_tap5), .dout (TDB_tap6));
  transistor_segment TDB_s6(.din (TDB_tap6), .dout (TDB_tap7));
  transistor_segment TDB_s7(.din (TDB_tap7), .dout (TDB_tap8));
  transistor_segment TDB_s8(.din (TDB_tap8), .dout (TDB_tap9));
  transistor_segment TDB_s9(.din (TDB_tap9), .dout (TDB_tap10));
  transistor_segment TDB_s10(.din (TDB_tap10), .dout (TDB_tap11));
  transistor_segment TDB_s11(.din (TDB_tap11), .dout (t_tap[12]));
  transistor_segment TDB_s12(.din (t_tap[12]), .dout (TDB_tap13));
  transistor_segment TDB_s13(.din (TDB_tap13), .dout (TDB_tap14));
  transistor_segment TDB_s14(.din (TDB_tap14), .dout (TDB_tap15));
  wire_segment WDB_seg_long0(.din (clk_in), .dout (WDB_long_mid0));
  wire_segment WDB_seg_long1(.din (WDB_long_mid0), .dout
       (WDB_long_mid1));
  wire_segment WDB_seg_long2(.din (WDB_long_mid1), .dout (w_tap_c));
  wire_segment WDB_seg_med0(.din (clk_in), .dout (WDB_med_mid));
  wire_segment WDB_seg_med1(.din (WDB_med_mid), .dout (w_tap_b));
  wire_segment WDB_seg_short(.din (clk_in), .dout (WDB_short_out));
  NAND2_X1 g128__8780(.A1 (n_1), .A2 (n_0), .ZN (clk_out));
  AOI222_X1 g129__4296(.A1 (t_tap[12]), .A2 (tuning_bits[2]), .B1
       (t_tap[4]), .B2 (tuning_bits[1]), .C1 (w_tap_b), .C2
       (tuning_bits[3]), .ZN (n_1));
  AOI22_X1 g130__3772(.A1 (tuning_bits[0]), .A2 (clk_in), .B1
       (w_tap_c), .B2 (tuning_bits[4]), .ZN (n_0));
endmodule

