`timescale 1ns/1ps

// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov  2 2025 14:09:47 CST (Nov  2 2025 20:09:47 UTC)

// Verification Directory fv/tunable_delay 

module transistor_segment(din, dout);
  input din;
  output dout;
  wire din;
  wire dout;
  wire mid_1, mid_2, mid_3, mid_4, mid_5;
  INV_X1 u_inv0(.A (din), .ZN (mid_1));
  INV_X1 u_inv1(.A (mid_1), .ZN (mid_2));
  INV_X1 u_inv2(.A (mid_2), .ZN (mid_3));
  INV_X1 u_inv3(.A (mid_3), .ZN (mid_4));
  INV_X1 u_inv4(.A (mid_4), .ZN (mid_5));
  INV_X1 u_inv7(.A (mid_5), .ZN (dout));
endmodule

module wire_segment(din, dout);
  input din;
  output dout;
  wire din;
  wire dout;
  wire w_mid_1, w_mid_2, w_mid_before_out;
  BUF_X1 u_buf_in(.A (din), .Z (w_mid_1));
  BUF_X1 u_buf_out_1(.A (w_mid_1), .Z (w_mid_2));
  BUF_X1 u_buf_out_2(.A (w_mid_2), .Z (w_mid_before_out));
  BUF_X1 u_buf_out_3(.A (w_mid_before_out), .Z (dout));
endmodule

module tunable_delay(clk_in, tuning_bits, clk_out);
  input clk_in;
  input [4:0] tuning_bits;
  output clk_out;
  wire clk_in;
  wire [4:0] tuning_bits;
  wire clk_out;
  wire [15:1] t_tap;
  wire TDB_tap1, TDB_tap2, TDB_tap4, TDB_tap5, TDB_tap6, TDB_tap7,
       TDB_tap8, TDB_tap9;
  wire TDB_tap10, TDB_tap11, TDB_tap12, TDB_tap14, TDB_tap15,
       WDB_long_mid0, WDB_long_mid1, WDB_med_mid;
  wire WDB_short_out, n_0, n_1, w_tap_b, w_tap_c;
  transistor_segment TDB_s0(.din (clk_in), .dout (TDB_tap1));
  transistor_segment TDB_s1(.din (TDB_tap1), .dout (TDB_tap2));
  transistor_segment TDB_s2(.din (TDB_tap2), .dout (t_tap[3]));
  transistor_segment TDB_s3(.din (t_tap[3]), .dout (TDB_tap4));
  transistor_segment TDB_s4(.din (TDB_tap4), .dout (TDB_tap5));
  transistor_segment TDB_s5(.din (TDB_tap5), .dout (TDB_tap6));
  transistor_segment TDB_s6(.din (TDB_tap6), .dout (TDB_tap7));
  transistor_segment TDB_s7(.din (TDB_tap7), .dout (TDB_tap8));
  transistor_segment TDB_s8(.din (TDB_tap8), .dout (TDB_tap9));
  transistor_segment TDB_s9(.din (TDB_tap9), .dout (TDB_tap10));
  transistor_segment TDB_s10(.din (TDB_tap10), .dout (TDB_tap11));
  transistor_segment TDB_s11(.din (TDB_tap11), .dout (TDB_tap12));
  transistor_segment TDB_s12(.din (TDB_tap12), .dout (t_tap[13]));
  transistor_segment TDB_s13(.din (t_tap[13]), .dout (TDB_tap14));
  transistor_segment TDB_s14(.din (TDB_tap14), .dout (TDB_tap15));
  wire_segment WDB_seg_long0(.din (clk_in), .dout (WDB_long_mid0));
  wire_segment WDB_seg_long1(.din (WDB_long_mid0), .dout
       (WDB_long_mid1));
  wire_segment WDB_seg_long2(.din (WDB_long_mid1), .dout (w_tap_c));
  wire_segment WDB_seg_med0(.din (clk_in), .dout (WDB_med_mid));
  wire_segment WDB_seg_med1(.din (WDB_med_mid), .dout (w_tap_b));
  wire_segment WDB_seg_short(.din (clk_in), .dout (WDB_short_out));
  NAND2_X1 g126__8780(.A1 (n_1), .A2 (n_0), .ZN (clk_out));
  AOI222_X1 g127__4296(.A1 (t_tap[3]), .A2 (tuning_bits[1]), .B1
       (w_tap_c), .B2 (tuning_bits[4]), .C1 (w_tap_b), .C2
       (tuning_bits[3]), .ZN (n_1));
  AOI22_X1 g128__3772(.A1 (tuning_bits[0]), .A2 (clk_in), .B1
       (t_tap[13]), .B2 (tuning_bits[2]), .ZN (n_0));
endmodule

